function getSearchesLikeThis(){
	var mlt =  {
		"unica":["project manager","qa","sas","weblogic","java"],
		"assembler":["cobol","mainframe"],
		"umts":["lte"],
		"chief information officer":["cio","vice president","cto","chief technology officer","it director"],
		"vcp":["vmware"],
		"sap product costing":["sap copa","sap fico"],
		"sap ps":["sap pp","sap sd","sap mm","sap abap","java developer"],
		"sap pp":["sap mm","sap apo","sap qm","sap sd","sap abap"],
		"sap po":["sap pi"],
		"sap pm":["sap plant maintenance","sap eam","sap mm","sap qm","sap pp"],
		"sap pi":["sap abap","sap basis","sap xi","sap sd","sap bw"],
		"front end web developer":["web designer","php"],
		"data entry":["customer service","receptionist","entry level","office assistant","administrative assistant"],
		"risk":["sas"],
		"cognos administrator":["cognos admin"],
		"ssis ssrs msbi":["siebel","teradata","php","salesforce","network engineer"],
		"dell":["java"],
		"sap mm/wm":["sap mm"],
		"software test":["software qa","software test engineer","qa tester","quality assurance","qa"],
		"it recruiter":["technical recruiter","it recruiter remote","business analyst","java developer","oracle developer"],
		"sql analyst":["data analyst","sql developer","business analyst"],
		"voip":["telecommunications","sip","telecom","voice","telephony"],
		"director information technology":["director it","it director"],
		"sap asset":["sap fi"],
		"oracle finance":["oracle functional","oracle financial"],
		"coolgen":["ca gen"],
		"vhdl":["fpga"],
		"sap hcm":["sap hr","sap abap","sap mm","sap payroll","successfactors"],
		"virtualization":["vmware"],
		".net c":["cto","microstrategy"],
		"idms":["ids"],
		"asic":["verilog","fpga","verification","c","protocol testing"],
		"sql administrator":["oracle dba","java developer"],
		"java telecommute":["java remote"],
		"oracle application dba":["oracle apps dba"],
		"net":["java",".net",".net developer"],
		"help desk technician":["help desk support"],
		"specialist":["analyst"],
		"oracle database developer":["oracle pl/sql developer"],
		"sap manager":["sap project manager","sap director","sap program manager","sap sd","sap mm"],
		"wodm":["ilog"],
		"work from home":["remote","business analyst","remote work","virtual","qa"],
		"security manager":["security director","cissp"],
		"compucom":["project manager"],
		"sun identity":["iam"],
		"big data architect":["hadoop"],
		"information technology":["it","desktop support","it manager","computer","system administrator"],
		"ivr tester":["qa tester"],
		"property":["business analyst"],
		"oracle apps techno functional":["oracle apps technical","oracle ebs developer","oracle apps developer","sap abap","obiee"],
		"application security":["penetration"],
		"manual tester":["qa tester","qa","manual testing","qa analyst","qa manual tester"],
		"recruiting manager":["recruiter"],
		"hardware engineer":["electrical engineer","fpga","test engineer","c"],
		"sap bobj developer":["sap bo developer","business objects developer"],
		"mobility":["mobile"],
		"unix":["linux","software","novell or netiq","solaris","aix"],
		"ssis developer":["sql developer","sql server developer","ssrs developer","java developer","sql"],
		"service desk":["help desk","desktop support","information technology","project manager"],
		"mobile architect":["exchange","mobile application developer","system engineer","ios developer","mobile developer"],
		"sap integration":["sap pi"],
		"swings":["asp.net"],
		"healthcare qa":["qa tester"],
		"etl informatica developer":["java developer",".net developer","sap fico"],
		"sap hcm ess mss":["webmaster .net"],
		"jd edwards":["jde","jdedwards","enterpriseone","jde developer","erp"],
		"web design":["graphic design","web designer","web developer"],
		"net developer":[".net developer",".net","java developer","informatica developer","business analyst"],
		"sap is retail":["sap mm"],
		"account manager":["sales","recruiter","business development manager","sales manager","account executive"],
		"erp":["jde","sap","jd edwards","oracle","project manager"],
		"business analyst $130,000":["business analyst $130"],
		"finance analyst":["business analyst"],
		"mq":["message broker","datapower","websphere","informatica","business analyst"],
		"qtp lead":["performance engineer"],
		"oracle application developer":["oracle ebs developer"],
		"aix administrator":["aix admin","unix administrator"],
		"fresher":["entry level"],
		"sap fico":["sap fi","sap mm","sap abap","sap sd","sap fico consultant"],
		"uat":["tax","qa","qa manager","sharepoint","business analyst"],
		"data analyst":["business analyst","data scientist","sql","etl","informatica"],
		"mainframe cobol":["cobol programmer","mainframe developer"],
		"sql database developer":["ssrs","sql server developer","ssis developer","ssis"],
		"websphere message broker":["wmb","websphere message broker developer","websphere mq","java","informatica developer"],
		"sap testing":["sap qa","sap tester","sap fico","sap mm","sap test lead"],
		"sharepoint":["sharepoint developer","sharepoint architect","sharepoint remote","sharepoint administrator",".net"],
		"ssrs ssis":["sql"],
		"actionscript":["flash"],
		"gate":["caps"],
		"talend developer":["informatica developer"],
		"lan":["network"],
		"abap developer":["sap abap"],
		"agile coach":["scrum master"],
		"gis qa":["abap","oracle dba"],
		"sap successfactors":["sap hcm","sap hr"],
		"president":["director"],
		"ab initio":["abinitio","sas","ab initio developer","java","informatica"],
		"business systems analyst":["business system analyst","project manager","qa analyst","mainframe","sap sd"],
		"it director":["it manager","cio","manager","vp it","cto"],
		"operations":["analyst","project manager","operations manager","data center","director"],
		"network security":["network engineer","network security engineer","information security","ceh","network administrator"],
		"telecom":["telecommunications","avaya","voip","director","analyst"],
		"oracle technical":["oracle apps technical","oracle ebs","oracle functional","oracle financials","oracle developer"],
		"computer tech":["help desk"],
		"mobile application developer":["iphone developer","system engineer","ios developer","exchange","iphone  developer"],
		"ventyx":["clicksoftware"],
		"fix":["java"],
		"server administrator":["urgent - project manager","project manager- agile/scrum","java gwt","oracle  adf","vmware administrator"],
		"writing":["writer"],
		"ims":["mainframe","cobol"],
		"production":["sap crm e-commerce","programmer linux python software software","3d visualization","software engineer","chief data officer"],
		"training manager":["trainer"],
		"budget analyst":["financial analyst","business analyst"],
		"pega":["hadoop","prpc","java","mainframe","business analyst"],
		"mcsa":["mcse","ccna","help desk"],
		"penetration":["security","application security"],
		"c   c":["sap sd","java"],
		"data stage developer":["datastage developer",".net developer","informatica developer"],
		"datawarehousing":["business analyst"],
		"ui designer":["web designer","visual designer","ux designer","web developer","front end developer"],
		"cloudera":["hadoop"],
		"vice president technology":["cio","director technology","c"],
		"clickschedule":["clicksoftware"],
		"tata consultancy services":["wipro","cognizant"],
		"oracle manager":["oracle dba"],
		"accion labs":["business analyst","qa","java developer"],
		"financial":["financial analyst","analyst"],
		"mdm":["informatica","informatica mdm","informatica developer","etl"],
		".net architect":[".net lead","application architect","software architect","c",".net developer"],
		"mapreduce":["hadoop"],
		"network":["network administrator","cisco","ccna","network engineer","noc"],
		"content":["writer","marketing"],
		"oracle pl sql developer":["oracle pl/sql developer","oracle pl/sql","pl/sql developer","plsql developer","pl/sql"],
		"forth":["upon"],
		"governance or cgeit or technology":["unix"],
		"telecommunication":["telecommunications"],
		"quality tester":["qa tester","quality analyst","qa analyst","qa","business analyst"],
		"data scientist":["data analyst","machine learning","big data","data science","hadoop"],
		"oracle database administrator":["oracle dba","dba","business analyst","informatica","linux"],
		"technical writer":["business analyst","instructional designer","technical writing","trainer","java"],
		"soapui":["qa"],
		"work at home":["unix","linux"],
		"urgent - project manager":["project manager- agile/scrum","java gwt","oracle  adf","oracle functional consultant","oracle tech"],
		"atg":["atg developer","business analyst","java","j2ee","teradata"],
		"project manager nj":["qa lead"],
		"bi architect":["business intelligence","data architect","cognos"],
		"sap qm":["sap pp","sap mm","sap pm","sap apo","sap bw"],
		"mvc":["c",".net","asp.net"],
		"cold fusion":["coldfusion"],
		"medicaid":["novell or netiq","unix","mmis","it project manager","weld"],
		"sap qa":["sap tester","sap test","sap testing","sap crm","sap fico"],
		"iib":["message broker"],
		"tier 1":["help desk"],
		"control-m":["mainframe","sas","oracle","project manager","pl/sql"],
		"mobile  developer":["android"],
		"chief technology officer":["cto","chief information officer","cio","vp"],
		"struts":["java"],
		"datastage developer":["java developer","oracle dba","informatica developer","etl developer",".net developer"],
		"websphere mq":["java","java developer","websphere message broker","mainframe"],
		"system admin":["system administrator","help desk","systems administrator","desktop support","oracle dba"],
		"agile project manager":["scrum master","business analyst"],
		"avaya":["telecom","voip","telecommunications","oracle apps dba","java developer"],
		"oracle hcm":["oracle hrms","oracle hr","oracle ebs"],
		"kristin.leigh@insourcenow.com":["zafar iconma","netsource","software development manager"],
		"forensic":["forensics"],
		"project":["project manager","project coordinator","coordinator","program","project management"],
		"software tester":["qa analyst","qa","qa tester","manual tester","software testing"],
		"fixed income":["business analyst"],
		"systems analyst":["system analyst","business analyst","data analyst","security","project manager"],
		"sap basis netweaver":["aix systems administrator"],
		"business intelligence":["cognos","business intelligence manager","business objects","data warehouse","ssrs"],
		"shell":["software engineering","protocol testing","verilog","test","c"],
		"angularjs":["javascript","java","angular","c",".net"],
		"healthcare ba":["business analyst healthcare","business analyst"],
		"quality assurance analyst":["qa analyst","qa tester","qa","manual tester","tester"],
		"solutions architect":["solution architect","java architect"],
		"user experience":["ux","user interface"],
		"rhce":["linux","red hat"],
		"firmware":["embedded"],
		"etl lead":["informatica","datastage"],
		"desktop manager":["it manager"],
		"program manager":["project manager","director","pmo","business analyst","product manager"],
		"salesforce developer":["salesforce administrator","business analyst","salesforce admin",".net developer","sfdc"],
		"programmer analyst":["business analyst","c"],
		"pentaho":["informatica","ssis","tableau","etl","hadoop"],
		"claims":["business analyst"],
		"software architect":["software manager","software engineer","c",".net architect","director"],
		"bsa":["business analyst"],
		"hyperion developer":["sql developer"],
		"chemistry":["business analyst"],
		"functional analyst":["business analyst"],
		"sap test":["sap qa","sap test lead","sap tester"],
		"infrastructure project manager":["it project manager","business objects"],
		"enterprise":["enterprise architect"],
		"supply chain":["sap","logistics","test","analyst","sap mm"],
		"tech writer":["technical writer"],
		"it administrator":["it manager","help desk"],
		"pki":["c"],
		"sap bobj":["sap bo","sap hana","sap bw","sap business objects","sap bi"],
		"data center operator":["computer operator"],
		"implementation":["project manager","data analyst","business analyst","analyst"],
		"helpdesk":["help desk","desktop","desktop support","technical support","support"],
		"ldap":["siteminder","oam"],
		"business development manager":["account manager"],
		"pega developer":[".net developer","informatica developer","java developer"],
		"oracle hr":["oracle hrms","oracle hcm"],
		"sfdc developer":["salesforce developer",".net developer"],
		"amazon":["java"],
		"report":["crystal","business intelligence","data","analyst","business objects"],
		"abinitio":["ab initio","etl","cognos","system analyst","market risk"],
		"pick programmer":["unidata"],
		"emc":["storage","emc storage","vnx","netapp","business analyst"],
		"sql database":["sql dba"],
		"emr":["ehr"],
		"release":["configuration","build","release manager","qa","business analyst"],
		"oracle retail":["retek","oracle rms"],
		"secretary":["administrative assistant"],
		"protocol testing":["physical design","software engineering","shell","support","asic"],
		"disaster":["disaster recovery"],
		"active directory":["exchange","help desk","desktop support","vmware","sccm"],
		"testing":["qa","manual testing","software testing","qa tester","test lead"],
		"analytics":["business analyst","business intelligence","data analytics","hadoop","data analyst"],
		"software director":["software manager"],
		"cics":["cobol","mainframe"],
		"sap remote":["sap abap","sap hana","sap sd","sap tester","sap bw"],
		"delphi":["c"],
		"3rd shift":["night shift","2nd shift","night","linux","help desk"],
		"master data":["sap"],
		"web developer":["web designer","front end developer","html","php","ui developer"],
		"teamcenter":["mainframe","sharepoint"],
		"test analyst":["qa analyst","tester","qa tester","manual tester","qa"],
		"application developer":["software developer","java developer","web developer","software engineer","java"],
		"wtx":["wmb","edi","cobol"],
		"customer service":["help desk","data entry","call center","technical support","customer support"],
		"oracle warehouse builder":["etl"],
		"html5":["javascript","web developer","python","java"],
		"packager":["sccm"],
		"sap treasury":["sap fico","sap fi",".net software architect","informatica architect","sap srm"],
		"reporting analyst":["data analyst","business analyst","business intelligence"],
		"sap vistex":["sap sd","sap abap"],
		"customer support":["customer service","tech support","help desk","helpdesk","qa"],
		"sap grc":["sap security","sap basis","sap security grc","sap abap","sap hana"],
		"oracle crm":["oracle service contracts","oracle ebs","oracle apps","salesforce","business analyst"],
		"sybase dba":["sap","oracle dba","network","java","entry"],
		"front end developer":["ui developer","web developer","web designer","javascript developer","front end web developer"],
		"oracle apex":["informatica"],
		"soap ui":["qa tester","qtp"],
		"telecommunications":["telecom","voip","telecommunications manager","telecommunication","voice"],
		"sap charm":["sap hana"],
		"firmware engineer":["embedded software engineer"],
		"basis":["sap basis"],
		"android developer":["mobile developer","java developer","ios developer","java","oracle dba"],
		"mobile project manager":["informatica"],
		"oracle financial":["oracle functional","oracle financials","oracle finance","oracle apps","oracle ebs"],
		"teradata dba":["java","informatica","hadoop","business analyst"],
		"sql data analyst":["sql developer"],
		"data warehouse architect":["data modeler","informatica","qa"],
		"oracle fusion":["java","oracle soa","sharepoint"],
		"aviation":["business analyst"],
		"(java or j2ee)":["sap and  abap","(production or support or maintenance)","informatica","java developer"],
		"javascript developer":["front end developer","ui developer","web developer","java","java developer"],
		"sap data conversion":["sap data migration"],
		"aix":["linux","aix remote","unix","aix administrator","business objects"],
		".net developers":[".net developer"],
		"business analysts":["business analyst"],
		"portfolio manager":["program manager"],
		"technical support":["desktop support","help desk","helpdesk","it support","it"],
		"product management":["product manager","director"],
		"voice":["voip","telecommunications"],
		"qa tester":["qa analyst","manual tester","business analyst","manual qa tester","qa manual tester"],
		"it":["it manager","information technology","help desk","it director","it support"],
		"business analyst health care":["business analyst healthcare","qa lead","java developer"],
		"oracle scm":["oracle ebs","oracle functional","oracle supply chain","oracle om","oracle apps"],
		"oracle reports":["pl/sql"],
		"ccnp":["ccna","network engineer","ccie","cisco","network"],
		"marketing analyst":["data analyst"],
		"ccna":["network","ccnp","cisco","network engineer","ccent"],
		"microstrategy developer":[".net developer","java developer","informatica developer","build release engineer","oracle dba"],
		"peoplesoft qa":["peoplesoft tester"],
		"mcse":["mcsa","vmware","systems administrator","ccna"],
		"sap master data":["sap mm","sap sd"],
		"data services":["bods","sap data services","etl"],
		"juniper":["network engineer","cisco","network"],
		"hana":["sap hana","business objects","bobj","sap bw","bw"],
		"2nd shift":["3rd shift"],
		"service-now":["servicenow"],
		"vistex":["sap sd","sap","abap"],
		"dynamics ax":["dynamics crm","microsoft dynamics ax","microsoft dynamics","sharepoint","java"],
		"hipaa":["healthcare","edi","business analyst"],
		"application support":["production support","technical support","application support analyst","application analyst","capgemini"],
		"maximo":["maximo consultant","maximo remote","java","informatica","sap basis"],
		"netezza":["informatica","obiee","etl","hadoop"],
		"quantitative":["sas"],
		"obiee":["obiee developer","informatica","business analyst","obia","hyperion"],
		"help desk":["desktop support","helpdesk","it support","support","technical support"],
		"bi publisher":["obiee","obiee developer"],
		"sap basis":["sap security","sap abap","sap bw","sap hana","sap basis administrator"],
		"solaris":["linux","unix","sccm","hadoop","network"],
		"sfdc":["salesforce","salesforce developer","salesforce administrator","salesforce.com","siebel"],
		"sap and  abap":["(java or j2ee)"],
		"judge":["qa"],
		"helpdesk manager":["help desk manager","it manager","help desk"],
		"network technician":["network administrator","help desk","desktop support","network engineer","network support"],
		"successfactors":["sap hcm","success factors","sap hr","sap","sap hana"],
		"agile":["scrum","project manager","scrum master","manager"],
		"management analyst":["sharepoint"],
		"sap mdg":["sap mdm","sap srm","sap mm","sap hana","sap bw"],
		"test lead":["qa lead","test manager","qa manager","qa","testing"],
		"sap mdm":["sap mdg","sap bw","sap mm","sap tester","sap hr"],
		"opt":["entry","sap","java"],
		"caps":["gate","igate"],
		"salesforce.com":["salesforce","sfdc","salesforce admin","salesforce developer","oracle dba"],
		"ui developer":["front end developer",".net developer","java developer","web developer","javascript developer"],
		"java developer":[".net developer","informatica developer","oracle dba","sql developer","business analyst"],
		"urgent - java developer":["oracle tech","project manager- agile/scrum","java gwt","oracle  adf","oracle functional consultant"],
		"bpc":["bw","sap bw","business objects"],
		"bpm":["ibm bpm","lombardi","oracle bpm","java","websphere"],
		"siebel admin":["siebel administrator"],
		"night":["3rd shift","shift","part time"],
		"sap benefits":["sap hcm"],
		"windows 7":["desktop","desktop support","sccm"],
		"security":["information security","security analyst","cissp","it security","cyber security"],
		"cybersecurity":["security"],
		"manual":["manual tester","qa","tester","manual testing","qa analyst"],
		".net lead":[".net architect",".net developer","java developer","mainframe","testing"],
		"webi":["business objects","sap business objects"],
		"intern":["internship","entry level","software intern","junior","entry"],
		"captiva":["documentum"],
		"icc":["zafar iconma","netsource"],
		"data migration":["data conversion"],
		"icd":["qa"],
		"sap instructional designer":["sap trainer"],
		"performance engineer":["performance tester","loadrunner","performance testing","load runner","qtp"],
		"marketing":["sales","marketing manager","public relations","analyst","advertising"],
		"statistician":["statistics","data scientist","sas programmer"],
		"quality assurance manager":["qa manager","quality assurance director","test manager","qa"],
		"sql bi developers":["ssrs developers","ssis developers"],
		"enterprise architect":["togaf","enterprise architecture","director","business architect","solution architect"],
		"sharepoint admin":["sharepoint administrator","java developer",".net developer",".net","qa"],
		"functional tester":["qa tester","qa","manual tester","qa analyst"],
		"oracle apps technical":["oracle ebs","oracle apps developer","oracle apps techno functional","oracle ebs technical","oracle ebs developer"],
		"sap solution manager":["sap basis","ilog","sap security","sap hana","sap sd"],
		"soc":["noc"],
		"experis":["randstad","kforce","java developer","modis","java"],
		"mba":["pmp","project manager","ab initio"],
		"oracle business analyst":["oracle scm","oracle functional","oracle financials","oracle ebs","obiee"],
		"storage administrator":["storage engineer"],
		"gis":["esri","gis analyst","arcgis","geospatial","gis qa"],
		"support":["help desk","desktop","technical support","it support","helpdesk"],
		"unix administrator":["linux administrator","unix system administrator","unix admin","aix administrator","system administrator"],
		"oracle projects":["oracle project accounting"],
		"wordpress":["php","javascript"],
		"editor":["writer","technical writer"],
		"vice president":["director","cio","cto","chief information officer","vp"],
		"it auditor":["it audit"],
		"computer operator":["data center operator","computer operations","noc","data center","as400"],
		"load runner":["performance tester","qtp","performance engineer","qa","loadrunner"],
		"sap sd":["sap mm","sap abap","sap fico","sap otc","sap bw"],
		"java/j2ee developer":["java developer",".net developer","java j2ee developer","websphere admin",".net"],
		"network engineer":["cisco","network administrator","ccnp","ccna","ccie"],
		"fpga":["asic","verilog","vhdl","hardware engineer","embedded"],
		"websphere commerce":["ecommerce","websphere admin"],
		"sap sm":["sap cs","sap sd"],
		"peoplesoft developer":["peoplesoft hcm","peoplesoft technical","business analyst","qa analyst"],
		"solar":["novell or netiq","linux","it project manager"],
		"msbi":["ssis","ssas","sql developer","sql server developer"],
		"operations manager":["it manager","project manager","business analyst"],
		"analyst":["business analyst","data analyst","project manager","systems analyst","data"],
		"oracle tech":["urgent - project manager","project manager- agile/scrum","java gwt","oracle  adf","oracle functional consultant"],
		"release engineer":["build engineer","configuration engineer","technical lead","configuration manager","release manager"],
		"bi analyst":["data analyst","business analyst","business intelligence"],
		"microsoft dynamics crm":["ext js","system analyst","vmware","ab initio","cognos"],
		"crystal":["crystal reports","report","bo","ssrs","business objects"],
		"ssrs developers":["sql bi developers","ssis developers"],
		"bidi":["bods"],
		"sap bo developer":["business objects developer","sap bobj developer","sap bobj","business objects"],
		"change manager":["release manager","change management","project manager","itil","program manager"],
		"qa lead":["test lead","qa manager","test manager","qa tester","java developer"],
		"qa test lead":["test manager","manual tester","qa tester","qa analyst","informatica"],
		"project scheduler":["project coordinator"],
		"application architect":[".net architect"],
		"accounting":["financial analyst","analyst","desktop","project manager"],
		"sap fico consultant":["sap basis"],
		"etl datastage":["datastage developer"],
		"excel":["vba","data analyst","analyst","excel vba","excel analyst"],
		"aix admin":["aix administrator","linux admin"],
		"sybase":["sybase developer","sybase dba","entry","oracle dba","oracle"],
		"computer science":["software","ccna","it","information technology","software engineer"],
		"interaction designer":["ux designer"],
		"test":["qa","quality","tester","testing","test lead"],
		"node":["javascript","angular"],
		"etl architect":["informatica","data architect","remote","informatica developer","etl developer"],
		"c++ developer":["c","software engineer"],
		"sap snc":["sap mm"],
		"sql":["sql developer","ssis","ssrs","sql server","sql dba"],
		"ssis ssrs":["ssis developer","sql developer","sql server developer","sql"],
		"sqa":["qa","tester","qa tester","qa analyst","analyst"],
		"weekend":["part time"],
		"tivoli":["tivoli access manager","vmware","java","security"],
		"disaster recovery":["business continuity"],
		"data warehouse testing":["etl testing"],
		"direct client - java developer":["windows server administrator","project manager- agile/scrum","oracle  adf","data warehouse etl","oracle  apps"],
		"qtp tester":["qa tester","manual tester","qa analyst","automation tester","qa"],
		"oracle service contracts":["oracle crm"],
		"security engineer":["cissp","network engineer","it security","information security","security analyst"],
		"unidata":["pick programmer"],
		"oracle fusion middleware developer":["oracle soa developer"],
		"linux admin":["linux administrator","unix admin","weblogic admin","java developer","linux system admin"],
		"manager":["director","it manager","project manager","program manager","architect"],
		"osb":["soa","unix","novell or netiq","linux","oracle soa"],
		"programmer linux python software software":["manager software","it","production","sap crm ecommerce","manager"],
		"ux designer":["interaction designer","ui designer","web designer"],
		"help desk manager":["service desk manager","it manager","helpdesk manager","support manager","it support"],
		"flash":["actionscript"],
		"sap portal":["webdynpro","sap hana","sap abap","abap","sap bw"],
		"dba":["oracle dba","sql","database","oracle","database administrator"],
		"datapower":["mq","websphere","project manager","websphere admin","middleware"],
		"sap security":["sap grc","sap basis","sap fico","sap bw","sap security grc"],
		"ba analyst":["qa analyst"],
		"natural adabas":["mainframe"],
		"data modeler":["data architect","data analyst","etl","hadoop","business analyst"],
		"sap tpm":["sap crm"],
		"php developer":["php web developer","web developer","software developer","java developer","tibco developer"],
		"ruby on rails":["java","javascript","c","python","developer"],
		"gatto":["22nd century technologies"],
		"director of technology":["it manager"],
		"jde":["jd edwards","jde developer","jdedwards","erp","rpg"],
		"qa etl":["qa tester"],
		"data manager":["business intelligence","project manager"],
		"pmp":["project manager","pmo","program manager","project","mba"],
		"r statistics":["ab initio","cognos"],
		"remedy developer":["java developer"],
		"cyber":["cyber security","security"],
		"sales manager":["account manager"],
		"c++ software engineer":["c"],
		"forensics":["forensic","security"],
		"portfolio":["pmo"],
		"pmo":["project manager","program manager","director","pmp","project"],
		"afghanistan":["intelligence analyst"],
		"crystal report":["crystal reports","business objects","bo","sap bo","ssrs"],
		"websphere administration":["websphere administrator"],
		"bo admin":["business objects administrator","business objects admin"],
		"aix systems administrator":["linux unix administrator","sap basis netweaver"],
		"ssis":["ssrs","sql","sql developer","ssas","sql server developer"],
		"modis":["randstad","business analyst","qa","java developer","ui developer"],
		"sap eam":["sap pm","sap plant maintenance"],
		"ibm bpm":["lombardi","hadoop","business analyst","datastage","oracle"],
		"oracle apps dba":["oracle applications dba","oracle ebs dba","oracle application dba","obiee","java"],
		"webmaster .net":["netsource","software python","trainer","blizzard","sap hcm ess mss"],
		"application analyst":["application support"],
		"enterpriseone":["jd edwards"],
		"change":["change management","change manager","itil","project manager"],
		"application packaging":["application packager","sccm"],
		"tibco admin":["business analyst"],
		"vb.net":[".net","vb6","asp.net","vba","c"],
		"software python":["webmaster .net","trainer","netsource","zafar iconma"],
		"software testing":["software tester","qa tester","software qa","qa","software quality assurance"],
		"pc technician":["desktop support","computer technician","help desk","pc support","desktop support technician"],
		"macintosh":["mac","apple"],
		"as400":["rpg","iseries","as/400","synon","cobol"],
		"oracle r12 developer":["oracle dba"],
		"team foundation server":["tfs"],
		"sas clinical":["sas programmer","clinical sas programmer","qa tester","java developer","cognos developer"],
		"businessobjects":["business objects","bo"],
		"sap tm":["sap sd","sap abap"],
		"software qa tester":["software qa analyst","manual tester","qa analyst"],
		"configuration engineer":["release engineer","build engineer"],
		"informatica admin":["informatica administrator","informatica developer","sas","business analyst","weblogic"],
		"f5":["network engineer"],
		"liquidity risk":["ab initio","abinitio","vmware","data modeler","cognos"],
		"soa developer":["oracle soa","oracle soa developer","oracle dba"],
		"perl":["perl developer","python","java","linux","oracle"],
		"iphone":["ios"],
		"msi":["application packager","installshield","sccm"],
		"business analyst insurance":["business analyst healthcare","business analyst finance"],
		"curriculum":["trainer"],
		"rhcsa":["linux","cissp"],
		"qa testing":["qa tester","qa analyst","manual testing","manual tester","business analyst"],
		"business process":["business analyst"],
		"sap lumira":["sap hana"],
		"business system analyst":["qa analyst","business systems analyst","business analyst healthcare","project manager","java"],
		"siebel":["business analyst","siebel developer","salesforce","siebel administrator","sap netweaver"],
		"project assistant":["project coordinator"],
		"sap bi":["sap bw","sap hana","sap abap","bw","sap bo"],
		"instructional":["instructional designer"],
		"ibm":["java","business analyst"],
		"sap bo":["sap bobj","business objects","sap bw","bobj","sap bi"],
		"machine learning":["data scientist","hadoop","big data"],
		"cism":["cissp","cisa"],
		"winforms":["c"],
		"cobol developer":["mainframe developer","mainframe","qa","business analyst"],
		"qc admin":["alm admin"],
		"sql  dba":["sql server dba"],
		"cisa":["cissp","cism"],
		"sap bw":["sap bi","sap hana","sap abap","sap basis","sap fico"],
		"sas administrator":["sas admin","informatica"],
		"mongo":["hadoop"],
		"nexus":["network engineer"],
		"visual designer":["ui designer"],
		"web content":["web producer"],
		"cisco network":["network engineer"],
		"exadata dba":["oracle dba"],
		"sap hcm functional":["sap hr"],
		"business analyst retail":["business analyst healthcare","qa tester","java developer"],
		"instructional designer":["technical writer","instructional design","trainer","elearning"],
		"oracle project accounting":["oracle projects"],
		"quality assurance engineer":["qa tester","quality assurance analyst","qa engineer","qa","qa analyst"],
		"product":["product manager"],
		"designer":["ux designer","graphic designer"],
		"share point":["sharepoint"],
		",net":[".net"],
		"sap data analyst":["informatica developer"],
		"azure":["hadoop","c",".net"],
		"mac":["macintosh","apple"],
		"oracle data integrator":["odi"],
		"tableau developer":["qlikview developer","informatica",".net developer","qlikview","salesforce developer"],
		"data":["data architect","data analyst","analyst","entry","sap"],
		"(pm or manager)":["java"],
		"telecommuting":["telecommute"],
		"java lead":["java developer","java architect","qa lead","java technical lead","informatica"],
		"qa engineer":["qa tester","qa analyst","manual tester","test engineer","selenium"],
		"fortran":["cobol"],
		"oracle manufacturing":["oracle ebs"],
		"sd":["sap sd","sap abap"],
		"soa":["oracle soa","osb","java","oracle","esb"],
		"siteminder":["ldap","weblogic","informatica","java","project manager"],
		"peoplesoft tester":["peoplesoft qa","qa","project manager"],
		"database architect":["data architect","oracle dba","sql","oracle"],
		"quality control":["quality assurance"],
		"sap scm":["sap fico","sap apo","sap pp","sap mm","sap sd"],
		"iseries":["as400","as/400","rpg","it director","data architect"],
		"systems engineer":["systems administrator","system administrator","it manager","windows engineer","system engineer"],
		"microstrategy":["java","microstrategy developer","tableau","business intelligence","hadoop"],
		"order management":["oracle"],
		"finance":["financial analyst","business analyst","java","analyst","informatica"],
		"sap edi":["sap sd","sap fico","sap pi","abap","sap crm"],
		"noc":["network","ccna","desktop support","help desk","network administrator"],
		"salesforce business analyst":["salesforce administrator"],
		"quality assurance director":["quality assurance manager","qa manager"],
		"technical support analyst":["desktop support"],
		"guidewire":["java","qa","classic asp","business analyst","informatica"],
		"rf engineer":["lte","qa","java"],
		"oracle bpm":["oracle soa"],
		"project engineer":["qtp"],
		"pl/sql developer":["oracle pl/sql developer","oracle developer","pl sql developer","java developer","oracle pl/sql"],
		"hyper-v":["vmware"],
		"project manager":["program manager","business analyst","project coordinator","pmp","it project manager"],
		"crm business analyst":["siebel"],
		"computer support":["help desk","computer technician","information technology","desktop support","software"],
		"automation tester":["qa tester","manual tester","qa analyst","java developer","qtp"],
		"it support":["desktop support","help desk","desktop","technical support","it specialist"],
		"sql database administrator":["sql dba","sql server dba"],
		"ms bi":["sql dba"],
		"powerbuilder":["informatica","pl/sql","hadoop","qa","sql"],
		"hcl":["wipro","cognizant","infosys","systel","igate"],
		"hcm":["hris","hrms","sap hcm"],
		"hibernate":["java"],
		"embedded software":["software engineer"],
		"cissp":["security","cisa","information security","cism","ceh"],
		"report analyst":["data analyst","sql"],
		"collabera":["business analyst","java","kforce","qa tester","qa"],
		"oracle financials":["oracle ebs","oracle r12","oracle financial","oracle applications","oracle functional"],
		"goldengate":["oracle dba"],
		"training":["trainer","instructional design","business analyst"],
		"sap tester":["sap qa","sap testing","sap sd","sap bw","qa tester"],
		"share point developer":["java developer","oracle dba"],
		"business objects":["bobj","bo","sap bo","business objects developer","sap business objects"],
		"atg developer":["java","informatica"],
		"etl developer":["informatica developer","java developer","informatica",".net developer","oracle dba"],
		"siteminder admin":["ldap admin"],
		"swing":["java"],
		"business architect":["enterprise architect","business analyst","director"],
		"business object developer":["business objects"],
		"redhat":["linux"],
		"spanish":["pmp"],
		"vp of it":["it director","cio"],
		"angular":["javascript","node","java","c","jquery"],
		"engineer":["electrical engineer","engineering","systems engineer","test engineer","mechanical engineer"],
		"iam":["sun identity","oim","identity","idm","security"],
		"sap cs":["sap sm"],
		"software development manager":["application development manager","zafar iconma","net matrix","kristin.leigh@insourcenow.com","architect"],
		"oracle wms":["oracle inventory","oracle functional"],
		"enterprise architecture":["enterprise architect"],
		"clinical":["oracle dba"],
		"application packager":["application packaging","installshield","msi","sccm","adminstudio"],
		"sap co":["sap fico","sap fi","sap copa","sap abap"],
		"webcenter":["adf"],
		"bobj":["business objects","bo","sap bo","sap bobj","hana"],
		"it project coordinator":["business analyst"],
		"zafar iconma":["icc","kristin.leigh@insourcenow.com","netsource","webmaster .net","software python"],
		"sap fi/co":["sap fico"],
		"r":["python","sas","java","hadoop","data analyst"],
		"windows engineer":["systems engineer","windows administrator","system engineer","system administrator"],
		"sap workflow":["abap","sap abap","sap fico","sap crm"],
		"director pmo":["program manager"],
		"system analyst":["business analyst","systems analyst","project manager","cognos","vmware"],
		"oracle  adf":["urgent - project manager","project manager- agile/scrum","java gwt","oracle functional consultant","oracle tech"],
		"san":["storage","vmware"],
		"retek":["oracle retail"],
		"net matrix":["software development manager"],
		"elearning":["instructional designer","instructional design"],
		"sas":["sas programmer","oracle dba","sas developer","sharepoint","sas analyst"],
		"engagement manager":["program manager","project manager"],
		"sap":["sap basis","sap fico","sap sd","sap bw","sap abap"],
		"java/j2ee":["java","ibm websphere message broker","java/j2ee developer","java developer","java j2ee developer"],
		"testing manager":["qa manager"],
		"cassandra":["hadoop","java","mongodb","big data","nosql"],
		"data warehouse etl":["direct client - java developer","oracle tech","urgent - project manager","project manager- agile/scrum","oracle  adf"],
		"java j2ee":["java developer","java j2ee developer","oracle soa","sharepoint","hadoop"],
		"wcf":[".net","wpf","c"],
		"performance":["loadrunner","performance test","performance engineer","qa","test"],
		"greenplum":["hadoop"],
		"immigration":["business analyst"],
		"java engineer":["java developer"],
		"ariba":["srm","business analyst","sap srm","sap"],
		"windows administrator":["system administrator","systems administrator","vmware administrator","network administrator","windows engineer"],
		"sql server":["ssis","sql server developer","ssrs","sql server dba","sql developer"],
		"siebel administrator":["siebel admin","hadoop"],
		"teradata developer":["informatica developer","informatica",".net developer","java developer","pl/sql developer"],
		"oracle applications developer":["oracle apps"],
		"senior":["director"],
		"cobol programmer":["mainframe cobol","mainframe","analyst"],
		"oracle apps developer":["oracle ebs developer","oracle apps technical","oracle applications","oracle dba","oracle ebs"],
		"oracle ebs developer":["oracle apps developer","oracle application developer","oracle apps techno functional","oracle apps","oracle apps technical"],
		"oracle pl sql":["oracle developer","oracle pl sql developer","oracle pl/sql developer","pl/sql","oracle pl/sql"],
		"program director":["program manager"],
		"data warehouse tester":["etl tester"],
		"business process analyst":["project manager"],
		"data modeling":["data modeler","data architect","data warehouse"],
		"mobile qa":["mobile tester","qa tester","tester","quality analyst","business analyst"],
		"assistant":["administrative","entry level"],
		"sap lead":["sap abap"],
		"mainframe tester":["manual tester"],
		"message broker":["mq","wmb","websphere message broker","iib","java"],
		"cisco engineer":["network engineer"],
		"mainframe developer":["cobol developer","java developer","cobol","business analyst","mainframe programmer"],
		"asp.net c":[".net"],
		"c++":["c","software engineer","java","c#","python"],
		"hyperion":["essbase","business analyst","obiee","hyperion developer","java"],
		"pl sql":["oracle developer","pl sql developer","pl/sql","oracle pl sql","plsql"],
		"installshield":["sccm","application packager","msi"],
		"sas developer":["sas programmer","etl developer",".net developer","sql dba","informatica developer"],
		"project manager healthcare":["business analyst healthcare","ba"],
		"qa test":["qa tester","qa analyst","quality assurance","oracle dba"],
		"mortgage":["business analyst","qa","abinitio","tibco","qa tester"],
		"objective c":["sccm"],
		"oracle apps functional":["oracle scm functional","oracle ebs functional","oracle apps dba","oracle ebs","informatica developer"],
		".net software architect":["sap treasury","sap srm"],
		"togaf":["enterprise architect","architect"],
		"biztalk developer":[".net developer"],
		"bo developer":["business objects developer","business objects",".net developer","bobj","sap bo"],
		"infrastructure":["it manager","infrastructure manager","information technology","architect","vmware"],
		"project manager $110,000":["project manager $110","business analyst"],
		"performance test":["loadrunner","qtp"],
		"websphere":["websphere admin","websphere administrator","weblogic","middleware","websphere remote"],
		"jr":["junior","entry","entry level","java"],
		"qa analyst contract":["qa tester"],
		"peoplesoft tam":["peoplesoft recruiting solutions"],
		"etl testing":["etl tester","data warehouse testing","qa analyst","qa","qa testing"],
		"cobol db2":["mainframe","qa"],
		"charles river":["business analyst"],
		"oracle apps":["oracle apps technical","oracle ebs","oracle applications","oracle functional","oracle apps developer"],
		"gwt":["java","java developer"],
		"electrical engineer":["hardware engineer","electronics engineer","software engineer","test engineer"],
		"oracle dba":["oracle apps dba","java developer","oracle database administrator","business analyst",".net developer"],
		"software engineer":["c","software developer","java","software engineer c","embedded software engineer"],
		"sap xi/pi":["sap pi"],
		"firewall":["security","checkpoint","cissp","network engineer","network"],
		"ccent":["ccna"],
		"pos":["it manager"],
		"sccm":["desktop","installshield","desktop engineer","application packaging","packager"],
		"etl test":["qa"],
		".net/c":["c"],
		"data warehousing":["business intelligence","etl","data warehouse","microstrategy"],
		"data mining":["data analyst","data scientist"],
		"performance analyst":["performance engineer"],
		"qlikview":["tableau","informatica","filenet","qlikview developer","qlikview remote"],
		"salesforce administrator":["salesforce developer","sfdc","salesforce admin","salesforce business analyst","business analyst"],
		"oracle ebs functional":["oracle apps functional"],
		"title:(business analyst)":["business analyst"],
		"office manager":["executive assistant","administrative assistant","administrative","project coordinator","project manager"],
		"business analyst":["project manager","qa","data analyst","business analyst healthcare","qa tester"],
		"java spring":["java j2ee","java remote","teradata"],
		"test engineer":["software test engineer","qa engineer","tester","qa tester","software engineer"],
		"spotfire":["qlikview","tibco","tableau","sas","informatica"],
		"tibco":["tibco developer","business analyst","java","hadoop","informatica"],
		"ruby":["python","rails","php","javascript","c"],
		"hadoop remote":["java remote"],
		"ms access":["vba","sql","business analyst","analyst","database"],
		"coordinator":["project","project coordinator","analyst","pmo","project manager"],
		"consultant":["analyst","business analyst","project manager","architect","manager"],
		"it technician":["help desk","computer technician","pc technician","it support","desktop support"],
		"coldfusion":["cold fusion","coldfusion developer","javascript","oracle","hadoop"],
		"technical director":["project manager"],
		"sharepoint architect":["sharepoint administrator","sharepoint manager","sharepoint consultant",".net developer","business analyst"],
		"middleware admin":["websphere admin","websphere administrator","websphere","weblogic admin","weblogic administrator"],
		"cq5":["aem","java","java developer","business analyst","vmware"],
		"qa manual":["qa tester","qa analyst","qa manual tester","java developer","manual tester"],
		"sap vc":["sap sd"],
		"telephony":["voip"],
		"cobol":["mainframe","cics","db2","project manager","mainframe cobol"],
		"ivr":["genesys"],
		"technology":["information technology","it manager","it","director","manager"],
		"process analyst":["business analyst"],
		"validation analyst":["validation engineer"],
		"program management":["program manager","pmo"],
		"physical design":["protocol testing","test"],
		"html":["web developer","web","web designer","sql","php"],
		"sap bpc":["sap bw","sap fico","sap basis","sap apo","sap hana"],
		"sharepoint consultant":["sharepoint architect"],
		"informatica tester":["etl tester","qa tester"],
		"web designer":["web developer","front end developer","graphic designer","graphic design","front end web developer"],
		"sterling":["edi","qa tester"],
		"oim":["iam","oam","idm","remote"],
		"title:sharepoint":["sharepoint"],
		"director":["manager","program manager","vp","it director","cto"],
		"technical lead":["build engineer","release engineer","qa lead"],
		"t-sql":["sql","sql developer"],
		"alfresco":["java"],
		"nosql":["hadoop","cassandra","big data","python","informatica"],
		"performance testing":["loadrunner","performance engineer","performance tester","qtp","project manager"],
		"oracle ebs":["oracle r12","oracle financials","oracle applications","oracle apps","oracle scm"],
		"sitecore":[".net"],
		"oracle functional":["oracle financial","oracle apps","oracle financials","oracle scm","oracle ebs"],
		"delivery manager":["program manager","director","project manager","it manager"],
		"change management":["itil","change manager","organizational change management"],
		"peoplesoft recruiting solutions":["peoplesoft tam"],
		"level 1":["entry level"],
		"oracle techno functional":["oracle apps techno functional","oracle ebs developer","oracle apps","sql developer","oracle apps dba"],
		"sap xi":["sap pi"],
		"sap isu":["sap abap"],
		"bank":["analyst"],
		"sap copa":["sap fico","sap product costing","sap co","sap fi"],
		"technical architect":["project manager"],
		"netapp":["vmware","storage","emc","netbackup","openstack"],
		"data science":["data scientist","hadoop"],
		"ldap admin":["siteminder admin","websphere admin"],
		"aml":["business analyst"],
		"data warehouse":["business intelligence","etl","data architect","data warehouse architect","datawarehouse"],
		"windows server":["vmware"],
		"oracle configurator":["oracle order management"],
		"edifecs":["edi"],
		"call center":["customer service","help desk","business analyst"],
		"c/c":["c"],
		"silverlight":["c"],
		"oracle oaf":["oracle apps","oracle soa"],
		"server":["support","network"],
		"build and release engineer":["java"],
		"sap technical":["sap abap","abap"],
		"cisco":["network","ccna","network engineer","ccie","ccnp"],
		"public relations":["marketing"],
		"sql bi":["sql developer","business objects","informatica developer","sql bi developer","ssis"],
		"software quality":["software qa"],
		"desktop analyst":["desktop support"],
		"market risk":["system analyst","abinitio","cognos","vmware","ab initio"],
		"technology manager":["it manager"],
		"unix system administrator":["unix admin",".net"],
		"bigdata":["hadoop","big data","qa","oracle dba","cognos"],
		"infrastructure manager":["it manager","it director","project manager"],
		".net mvc":["c"],
		"java gwt":["urgent - project manager","project manager- agile/scrum","oracle  adf","oracle functional consultant","oracle tech"],
		"scrum master":["project manager","agile project manager","agile coach","business analyst","qa manager"],
		"oracle brm":["salesforce"],
		"business":["business analyst","business objects","business systems analyst","business intelligence","software"],
		"internship":["intern","entry level","entry"],
		"sharepoint remote":["sharepoint developer"],
		"sap business objects data services":["sap bods"],
		"linux unix administrator":["aix systems administrator"],
		"datacenter":["data center","vmware"],
		"front end":["front end developer","web developer","javascript"],
		"copywriter":["writer"],
		"srm":["ariba","sap srm"],
		"cto or cio or vp":["novell or netiq","it project manager","unix","linux"],
		"backup":["netbackup"],
		"trade support":["autosys"],
		"ecommerce":["websphere commerce","project manager","analyst","director"],
		"websphere admin":["websphere administrator","java developer","middleware admin","weblogic admin",".net developer"],
		"manual test":["tester","manual tester","qa","qa tester"],
		"as/400":["as400","iseries","rpg","obiee","java"],
		"actuate":["birt"],
		"sap finance":["sap fi","sap fico"],
		"ehr":["emr"],
		"teksystems":["kforce","business analyst"],
		"liferay":["java","hadoop"],
		"sql ssis":[".net"],
		"cransoft":["cognos"],
		"emc storage":["storage engineer","business analyst"],
		"oracle soa":["oracle dba","oracle adf","cognos","oracle soa developer","java developer"],
		"embedded":["firmware","c","embedded software","software engineer","embedded software engineer"],
		"sap netweaver":["siebel","sap fico",".net",".net developer","java"],
		"c   developer":["oracle soa","oracle","mainframe","java developer","java"],
		"test manager":["qa manager","test lead","qa lead","qa","test architect"],
		"weblogic admin":["weblogic administrator","soa admin","linux admin","java developer","websphere"],
		"healthcare tester":["qa tester"],
		"websphere remote":["websphere admin"],
		"websphere portal":["java","websphere portal developer","java developer"],
		"ab":["ab initio"],
		"development manager":["software manager","application development manager","software development manager","director","java"],
		"sales":["account manager","account executive","business development","marketing","sales engineer"],
		"objective-c":["ios"],
		"ssrs":["ssis","sql","ssas","sql developer","bi developer"],
		"oracle rac":["oracle dba"],
		"ax":["dynamics ax"],
		"informatica administrator":["informatica admin","informatica developer","weblogic","etl","business analyst"],
		"mobile tester":["qa tester","mobile qa","mobile testing","qa","qa engineer"],
		"storage":["emc","san","netapp","storage administrator","storage engineer"],
		"workday":["peoplesoft","workday hcm","hris","sap hr","informatica"],
		"sap eh":["sap ehs","sap plm"],
		"hybris":["sap hybris","java"],
		"oracle functional consultant":["urgent - project manager","project manager- agile/scrum","java gwt","oracle  adf","oracle tech"],
		"application support analyst":["production support","business analyst"],
		"siebel developer":["sap basis","qa","oracle dba"],
		"java developer hadoop":["sap abap"],
		"sap p2p":["sap mm"],
		"oracle bpel":["oracle soa","java"],
		"technical manager":["technical project manager","project manager","data modeler","cognos","oracle dba"],
		"remote":["telecommute","work from home","virtual","business analyst","java"],
		"solution architect":["solutions architect","enterprise architect","java","aix","data architect"],
		"business intelligence developer":["ssrs"],
		"system engineer":["system administrator","ios developer","iphone developer","mobile application developer","exchange"],
		"scm":["build release","oracle scm","configuration manager","oracle soa"],
		"webmethods":["sap","java","qa","sap pi","edi"],
		"peoplesoft dba":["peoplesoft administrator","peoplesoft admin","peoplesoft upgrade","oracle dba"],
		"helpdesk support":["desktop support","it support","technical support"],
		"novell or netiq":["medicaid","unix","linux","weld","solar"],
		"business analyst financial":["business analyst banking"],
		"data warehouse developer":["etl","informatica developer"],
		"program":["program manager","project","director","manager","project manager"],
		"wmb":["message broker","wtx","websphere message broker"],
		"sap training":["sap trainer"],
		"sap crm":["sap abap","sap sd","sap mm","sap bw","sap fico"],
		"r12":["oracle","oracle r12"],
		"sap wm":["sap mm","sap sd","sap ewm","sap le","sap abap"],
		"network operations":["network support","noc"],
		"software developer":["software engineer","web developer","application developer",".net developer","programmer"],
		"etl tester":["qa tester","etl qa","business analyst","qa analyst","etl testing"],
		"account executive":["sales","account manager","project manager"],
		"bi tester":["qa tester"],
		"dotnet":[".net","sharepoint",".net developer"],
		"lisa":["qa"],
		"essbase":["hyperion",".net"],
		"it manager":["it director","information technology","project manager","it project manager","infrastructure manager"],
		"configuration management":["configuration manager","release engineer"],
		"obiee developer":["java developer","informatica developer","oracle dba",".net developer","cognos developer"],
		"design":["graphic design","web design"],
		"webdynpro":["abap","sap portal","sap","sap basis"],
		"oracle p2p":["oracle purchasing"],
		"xcelsius":["business objects","bobj"],
		"top secret":["clearance","sccm","systems administrator","it manager","network"],
		"entry-level":["entry level"],
		"sap crm functional":["sap sd"],
		"mule":["java","qtp","hadoop"],
		"sap srm":["sap mm","sap abap","sap bw","sap sd","sap hana"],
		"kronos":["informatica","peoplesoft","java developer","oracle dba","java"],
		"success factors":["successfactors"],
		"technical recruiter":["it recruiter","business analyst","qa tester"],
		"cognos developer":["oracle dba","sap abap","business analyst","datastage","informatica developer"],
		"oracle pl/sql developer":["oracle pl sql developer","java developer","oracle database developer","qa tester","java"],
		"compliance":["security"],
		"advertising":["marketing"],
		"pick":["pick programmer"],
		"qa selenium":["business analyst","java developer","qa tester","performance engineer",".net"],
		"sap crm e-commerce":["production","technical writer","programmer linux python software software","python","project"],
		"oscp":["ceh"],
		"trainer":["training","technical trainer","webmaster .net","instructional designer","technical writer"],
		"access developer":["vba"],
		"graphic design":["graphic designer","web design","web designer","photoshop"],
		"vc":["c"],
		"trainee":["entry level"],
		"documentation specialist":["technical writer"],
		"sap basis administrator":["sap sd","cognos"],
		"esri":["gis"],
		"hexaware":["java developer",".net"],
		"sap crm technical":["sap abap"],
		"h1b":["java","c"],
		"sharepoint  developer":["sap bw"],
		"selenium tester":["qa analyst","qa tester","manual tester",".net developer","java developer"],
		"qa analyst":["qa tester","business analyst","tester","manual tester","qa engineer"],
		"tester":["qa","qa tester","qa analyst","manual tester","business analyst"],
		"director of food and beverage":["unix"],
		"sap testing lead":["sap test lead"],
		"oracle purchasing":["oracle p2p"],
		"network administrator":["system administrator","network engineer","systems administrator","network admin","desktop support"],
		"salesforce":["salesforce developer","sfdc","business analyst","salesforce administrator","salesforce remote"],
		"business analyst $80":["business analyst $80,000"],
		"sap trainer":["sap instructional designer","sap training","sap bi","sap bw"],
		"visual basic":["vb","vba","c",".net"],
		"red hat":["linux","rhce","unix"],
		"tibco developer":["java developer","informatica developer","php developer","sql dba"],
		"netbackup":["backup","netbackup remote","netapp","cissp","it helpdesk"],
		"qa tester healthcare":["qtp"],
		"business analyst $130":["business analyst $130,000"],
		"executive assistant":["administrative assistant","office manager","analyst"],
		"graphic designer":["graphic design","web designer","qtp"],
		"information":["information technology","information security","it manager"],
		"oracle bi":["obiee"],
		"sap bi bw":["sap bi/bw","sap hana"],
		"sap bods":["sap data services","sap hana","sap bw","sap business objects data services","sap bobj"],
		"pl/sql":["pl/sql developer","oracle","oracle pl/sql","plsql","java"],
		"oracle pdh":["oracle pim"],
		"csv":["validation"],
		"css":["html","php","java"],
		"oracle soa developer":["oracle fusion middleware developer","oracle dba","websphere","obiee developer","weblogic admin"],
		"embedded engineer":["embedded software engineer"],
		"qlikview developer":["tableau developer","java developer","business analyst","sap apo","sharepoint developer"],
		"java manager":["java architect"],
		"a":["ccna","help desk","desktop support"],
		"documentation":["technical writer"],
		"django":["python"],
		"hfm":["hyperion"],
		"sql remote":["ssis","c"],
		"mobile developer":["ios developer","ios","android developer","mobile application developer","iphone  developer"],
		"photoshop":["graphic design"],
		"it specialist":["it support","desktop","desktop support","information technology","help desk"],
		"sap hr":["sap hcm","sap abap","sap payroll","sap mm","sap hana"],
		"help":["help desk","support","desktop support","desktop","it"],
		"build and release":["java developer"],
		"sap test manager":["sap test lead"],
		"developer":["programmer","web developer","java",".net developer","c"],
		"sap test lead":["sap testing lead","sap tester","sap test manager","sap testing","sap qa"],
		"selenium":["qa","qtp","automation","java","qa tester"],
		"user interface":["user experience"],
		"systems":["systems administrator","systems analyst","systems engineer","administrator","it manager"],
		"etl qa":["etl tester","sql tester","qa tester","tester","qa analyst"],
		"sap data services":["sap bods","bods","sap hana","etl","informatica"],
		"evening":["night shift"],
		"ceh":["cissp","security","oscp","penetration tester","network security"],
		"business development":["sales","business development manager","business analyst"],
		"chief data officer":["3d visualization","programmer linux python software software","production","sap crm ecommerce","sap crm e-commerce"],
		"edi tester":["qa","qa tester"],
		"sap fi":["sap fico","sap fscm","sap co","sap tester","sap sd"],
		"vmware administrator":["windows administrator","server administrator","urgent - project manager","project manager- agile/scrum","java gwt"],
		"linux engineer":["linux administrator"],
		"data conversion":["data migration"],
		"oracle developer":["pl/sql developer","oracle pl/sql developer","oracle pl sql developer","oracle dba","plsql developer"],
		"lombardi":["ibm bpm","bpm"],
		"mainframes":["mainframe","cobol","java","oracle dba"],
		"test coordinator":["qa"],
		"operation":["data"],
		"insurance":["manager","cobol"],
		"research":["data analyst"],
		"health":["healthcare"],
		"project manager $120,000":["program manager","sharepoint"],
		"asp":["vb",".net","asp.net","c","sharepoint"],
		"ios":["ios developer","android","mobile developer","mobile","ios remote"],
		"service desk manager":["help desk manager","it manager"],
		"crystal reports developer":["business analyst",".net developer","java"],
		"qa jobs":["qa tester"],
		"oracle erp":["oracle ebs","oracle r12","oracle applications","oracle apps","oracle scm"],
		"drupal":["php","business analyst"],
		"gentran":["sterling integrator","edi"],
		"tech mahindra":["infosys","cognizant","igate","wipro","qa"],
		"proposal writer":["technical writer"],
		"linux systems administrator":["unix systems administrator"],
		"mongodb dba":["oracle dba"],
		"sql server database administrator":["sql server dba"],
		"adminstudio":["application packager"],
		"wpf":["c",".net","c#","asp.net","wcf"],
		"igate":["wipro","hcl","caps","tech mahindra","cognizant"],
		"service delivery":["itil","project manager"],
		"tata":["wipro"],
		"rails":["ruby","ruby on rails","javascript","ios"],
		"checkpoint":["firewall","network engineer"],
		"oracle scm functional":["oracle apps functional"],
		"weblogic":["weblogic admin","websphere","middleware","oracle dba","weblogic administrator"],
		"entry developer":["web developer"],
		"storm":["hadoop"],
		"windows 7 migration":["desktop support"],
		"bi manager":["informatica"],
		"ba healthcare":["business analyst"],
		"instructional design":["instructional designer","trainer","technical writer","elearning","training"],
		"datawarehouse":["data warehouse","etl","informatica","business analyst","informatica developer"],
		"quality assurance tester":["qa tester","qa analyst","manual tester","software tester","quality assurance analyst"],
		"technical analyst":["business analyst","java"],
		"sql server developer":["ssis","ssis developer",".net developer","java developer","ssrs"],
		"tfs":["team foundation server"],
		"dot net":[".net",".net developer","java developer","java","dot net developer"],
		"jquery":["javascript","angular",".net"],
		"backend tester":["qa tester","etl tester","manual tester"],
		"architect":["director","enterprise architect","manager","java","java architect"],
		"business continuity":["disaster recovery","project manager"],
		"oracle plsql":["oracle developer"],
		"java websphere":["java developer"],
		"cognizant":["wipro","hcl","infosys","capgemini","project manager"],
		"infosys":["wipro","cognizant","hcl","tech mahindra","qa lead"],
		"project lead":["business analyst","project coordinator"],
		"oracle consultant":["oracle functional consultant","oracle soa","data architect"],
		"oracle pim":["oracle mdm","oracle pdh"],
		"qa test engineer":["qa tester","tester"],
		"jsf":["java"],
		"quality analyst":["business analyst","qa tester","qa analyst","qa","tester"],
		"jsp":["java"],
		"lotus notes developer":["business analyst"],
		"data architect":["data modeler","data warehouse architect","data warehouse","database architect","etl"],
		"vnx":["emc"],
		"j2ee developer":["java developer","java","java lead","sap abap","sap basis"],
		"mobile":["android","ios","mobile developer","java","mobile architect"],
		"part-time":["part time","remote"],
		"part":["part time"],
		"microsoft":["sccm","it","desktop support","sharepoint","linux"],
		"oracle mdm":["oracle pim"],
		"remote qa":["tester"],
		"ab initio developer":["oracle dba","abinitio developer",".net developer","java developer","etl developer"],
		"node.js":["php","javascript","java","c"],
		"unix admin":["linux admin","unix system administrator","unix administrator","weblogic admin","qlikview"],
		"exstream":["cobol","java"],
		"jboss":["websphere","weblogic","linux","hadoop","java"],
		"prpc":["pega"],
		"big data":["hadoop","big data architect","java","data scientist","informatica"],
		"writer":["technical writer","editor","writing","copywriter","content"],
		"weblogic administrator":["weblogic admin","websphere admin","middleware admin","qa","pl/sql developer"],
		"sap crm ecommerce":["programmer linux python software software","chief data officer","sap crm e-commerce","python","technical writer"],
		"angular js":["java"],
		"computer operations":["computer operator"],
		"python developer":[".net developer"],
		"sas analyst":["sas programmer","data analyst"],
		"remedy":["bmc remedy","itsm","sharepoint","itil","it"],
		"it helpdesk":["netbackup","cissp","desktop support"],
		"veeva":["salesforce"],
		"oracle forms":["pl/sql","oracle developer","oracle pl/sql","pl/sql developer","oracle pl/sql developer"],
		"sql dba":["sql server dba","sql developer","sql database administrator","oracle dba","business analyst"],
		"banking":["business analyst"],
		"netsource":["webmaster .net","software python","zafar iconma","trainer","icc"],
		"crm":["sap crm","siebel","salesforce","business analyst","dynamics crm"],
		"intelligence":["business intelligence","business analyst"],
		"network manager":["it manager","network engineer","network director","network administrator","cisco"],
		"migration":["desktop","desktop support"],
		"oracle  apps":["oracle tech","urgent - project manager","java gwt","server administrator","oracle  adf"],
		"oracle pl/sql":["oracle developer","pl/sql developer","oracle pl/sql developer","oracle pl sql developer","java developer"],
		"informatica lead":["crystal reports","sap hana","sharepoint","informatica developer","obiee"],
		"peoplesoft hrms":["peoplesoft hcm"],
		"sap otc":["sap sd","sap bw"],
		"genesys":["ivr","project manager"],
		"sap ip":["sap bw"],
		"javascript":["php","angular","java","python","web developer"],
		"quality center":["qa tester"],
		"it infrastructure":["it manager"],
		"french":["business analyst"],
		"solr":["hadoop","java"],
		"capgemini":["cognizant","wipro","hcl","systel","infosys"],
		"c":[".net","c++","c#","software engineer","asp.net"],
		"title:(project manager)":["project manager"],
		"computer technician":["pc technician","desktop support","help desk","it","it technician"],
		"c   java":["ab initio","cognos"],
		"java developers":["java developer",".net developer"],
		"night shift":["3rd shift","evening","cissp","business analyst"],
		"design engineer":["mechanical engineer"],
		"release manager":["change manager","project manager","release engineer","configuration manager","build engineer"],
		"soa tester":["qa tester"],
		"linux":["unix","linux administrator","aix","rhce","linux admin"],
		"desktop":["desktop support","helpdesk","help desk","support","it"],
		"java":["java developer","hadoop",".net","java j2ee","j2ee"],
		"pmo analyst":["project coordinator","project manager"],
		"(production or support or maintenance)":["(java or j2ee)"],
		"pc":["pc support","help desk","desktop","it"],
		"secret":["clearance"],
		"peoplesoft administrator":["peoplesoft admin","peoplesoft dba","peoplesoft upgrade","business analyst"],
		"pm":["project manager"],
		"information technology manager":["it manager"],
		"business analysis":["business analyst"],
		"servicemix":["enterprise integration patterns","camel"],
		"asp.net developer":[".net developer","java developer","informatica developer","c",".net"],
		"sap ehsm":["sap ehs"],
		"instructor":["trainer"],
		"configuration manager":["release engineer","release manager","build engineer","configuration management","build release"],
		"mainframe programmer":["mainframe developer"],
		"hyperion essbase":["informatica"],
		"it business analyst":["project manager"],
		"report developer":["ssrs","sql developer","etl","business intelligence","business objects"],
		"mainframe":["cobol","business analyst","qa","informatica","mainframe developer"],
		"shift":["3rd shift","night"],
		"sterling integrator":["gentran","edi","business analyst"],
		"software qa engineer":["qa analyst","software test engineer","qa tester","java"],
		"project coordinator":["project manager","business analyst","project analyst","analyst","project management"],
		"desktop support manager":["it manager"],
		"business objects administrator":["bo admin","business objects admin"],
		"websphere administrator":["websphere admin","java developer","websphere portal administrator","cognos","middleware administrator"],
		"vcloud":["vmware"],
		"ccna ccnp":["network engineer","business analyst"],
		"clerical":["receptionist","administrative assistant","administrative","desktop support"],
		"hadoop":["java","big data","hadoop developer","hive","cassandra"],
		"data center manager":["it manager"],
		"development":["development manager"],
		"big data developer":["hadoop developer"],
		"ccie":["cisco","ccnp","network engineer","ccna","network"],
		"optim":["hadoop"],
		"obia":["obiee"],
		"microsoft dynamics":["dynamics ax","dynamics crm",".net"],
		"financial analyst":["business analyst","finance","data analyst","accounting","budget analyst"],
		"information systems":["information technology"],
		"database":["database administrator","dba","sql","sql server","oracle"],
		"iphone developer":["ios developer","mobile application developer","system engineer","exchange","mobile developer"],
		"qa consultant":["qa tester"],
		"peoplesoft admin":["peoplesoft administrator","peoplesoft dba","business analyst"],
		"business analyst banking":["business analyst financial","business analyst finance","java developer"],
		"sap plm":["sap ppm","sap ehs","sap eh","sap pp","sap mm"],
		"entry":["junior","entry level","network","help desk","data"],
		"demantra":["oracle"],
		"clearance":["top secret","secret","cissp","information security","security"],
		"sap hana":["sap bw","sap basis","sap bi","sap bobj","sap abap"],
		"software manager":["software development manager","development manager","software engineering manager","software director","c"],
		"alm admin":["qc admin"],
		"desk":["support","desktop"],
		"it security":["information security","security analyst","it manager","security engineer","it director"],
		"it support technician":["desktop support"],
		"mysql":["php","python","oracle dba"],
		"openstack":["cloud","vmware","netapp"],
		"manual testers":["manual tester"],
		"webfocus":["informatica","oracle","qa","project manager","cobol"],
		"pc support":["desktop support","help desk","pc technician","it support","desktop"],
		"unix support":["autosys","production support"],
		"ext js":["extjs","microsoft dynamics crm","ab initio","vmware","project manager"],
		"automation lead":["test lead","qtp"],
		"java architect":["java lead","solutions architect","java manager","java developer","qa tester"],
		"qa manager":["test manager","qa director","qa lead","test lead","quality assurance manager"],
		"sap bi/bw":["sap bw","java","sap bi bw","qtp","sap bi"],
		"administrative":["administrative assistant","assistant","clerical","office manager","entry level"],
		"build":["build release","build and release","release","build release engineer","build engineer"],
		"manage":["project manager"],
		"big":["big data"],
		"oracle ebs technical":["oracle apps technical"],
		"sql developer":["sql server developer","ssis","java developer",".net developer","ssis developer"],
		"documentum":["informatica","captiva","cognos","sharepoint","business analyst"],
		"c# developer":["c",".net developer",".net"],
		"facets":["healthcare","healthcare business analyst","business analyst","ba","business analyst healthcare"],
		"project manager $110":["project manager $110,000"],
		"telecommute":["remote","telecommuting","virtual","c","work from home"],
		"communications":["marketing"],
		"vsphere":["vmware"],
		"spring":["java","hadoop"],
		"sap ewm":["sap mm","sap wm","sap abap","sap apo","sap sd"],
		"dodd frank":["business analyst"],
		"sas data analyst":["sas programmer"],
		"build release engineer":["microstrategy developer","sas","project manager","informatica developer","oracle soa"],
		"sap abap developer":["java developer","sap fico","oracle dba","sap crm"],
		".net developer":["java developer","informatica developer","sql developer","oracle dba","net developer"],
		"system administrator":["systems administrator","network administrator","help desk","desktop support","system engineer"],
		"qa manual tester":["qa analyst","qa manual testing","manual testing","qa testing","informatica developer"],
		".net programmer":[".net developer"],
		"oracle adf":["oracle soa","server administrator","oracle functional consultant","oracle tech","data architect"],
		"scala":["java","hadoop"],
		"oracle remote":["oracle dba"],
		"jdedwards":["jd edwards","jde"],
		"integration":["sap bw"],
		"web services":["selenium","qa"],
		"epic":["epic trainer"],
		"vp engineering":["cto"],
		"teradata":["informatica","teradata developer","etl","teradata dba","business analyst"],
		"ba":["business analyst","qa","healthcare","quality analyst","business analyst healthcare"],
		"it project management":["it project manager","project manager"],
		"informatica":["informatica developer","etl","business analyst","cognos","java"],
		"bo":["business objects","bobj","sap bo","crystal reports","businessobjects"],
		"bi":["sql","etl","cognos","java","business intelligence"],
		"sap webdynpro":["sap hcm","sap abap"],
		"bw":["sap bi","sap bw","hana","sap bw/bi","bpc"],
		"uft":["qtp"],
		"ids":["cobol","idms"],
		"bgp":["ccnp"],
		"it audit":["it auditor"],
		"idm":["oim","iam"],
		"manual qa":["qa tester","manual tester","qa analyst","manual testing","qa engineer"],
		"loganbritton":["java developer"],
		"windows admin":["system admin","windows administrator","system administrator","java developer"],
		"manual testing":["manual tester","qa tester","qa","selenium","qa testing"],
		"statistics":["statistician","sas","data analyst","analyst","hadoop"],
		"performance tester":["performance engineer","load runner","qa tester","loadrunner","qa analyst"],
		"systems admin":["systems administrator"],
		"java programmer":["java developer",".net developer"],
		"jboss admin":["weblogic admin"],
		"healthcare project manager":["program manager"],
		"websphere application server":["websphere admin"],
		"appian":["business analyst"],
		"sap director":["sap project manager","sap program manager","sap manager","sap bw","sap mm"],
		"it support specialist":["desktop support"],
		"sql server dba":["oracle dba",".net developer","java developer","business analyst","java"],
		"junior":["entry","entry level","jr","java","intern"],
		"informatica developer":["java developer","etl developer",".net developer","etl informatica developer","business analyst"],
		"groovy":["java"],
		"it project manager":["technical project manager","it program manager","business analyst","medicaid","project coordinator"],
		"ux":["user experience","ux designer","java"],
		"middleware":["websphere","weblogic","soa","datapower","weblogic admin"],
		"cio":["cto","chief information officer","director","vice president","it director"],
		"windows":["vmware","desktop","windows administrator","windows 7","system administrator"],
		"ui":["ui developer","java","html","qa","web developer"],
		"verification":["asic"],
		"sharepoint administrator":["sharepoint admin","sharepoint developer","sharepoint architect","java developer","business analyst"],
		"fico":["sap fico","sap","sap abap","business analyst","java"],
		"synechron":["business analyst","qa"],
		"oracle applications dba":["oracle apps dba","oracle ebs dba"],
		"supervisor":["manager"],
		"human resources":["hr","project manager","qa","program manager","oracle dba"],
		"service delivery manager":["it manager","project manager"],
		"manual qa tester":["manual testing","qa analyst"],
		"engineering":["software","engineer","informatica","unix","java"],
		"data governance":["informatica","project manager","oracle dba"],
		"associate project manager":["project coordinator"],
		"network security engineer":["vmware"],
		"database analyst":["data analyst","sql"],
		"pl sql developer":["pl/sql developer","oracle developer","pl/sql","oracle pl sql developer","oracle pl/sql developer"],
		"java, or j2ee":["sql dba","sql developer"],
		"entry level":["junior","help desk","intern","information technology","internship"],
		"application":["application support"],
		"electrical":["electrical engineer"],
		"grc":["java"],
		"jcl":["cobol","mainframe"],
		"cyber security":["information security","information technology","system administrator","help desk","linux"],
		"manual qa engineer":["manual tester"],
		"validation engineer":["validation analyst","java developer","informatica developer","test engineer","manual tester"],
		"mongodb":["hadoop","cassandra"],
		"scrum":["scrum master","agile","project manager","manager","business analyst"],
		"program coordinator":["project coordinator"],
		"health care business analyst":["healthcare business analyst"],
		"sap business objects":["sap bo","sap bobj","sap hana","sap bw","bobj"],
		"qa automation tester":["manual tester","qa analyst"],
		"splunk":["hadoop","business analyst","informatica","big data"],
		"sap project manager":["sap program manager","sap director","sap fico","sap hana","sap basis"],
		"embedded software engineer":["firmware engineer"],
		"vice":["director","vp","cio","vice president"],
		"information assurance":["information security","cissp","security","help desk","security analyst"],
		"oracle":["oracle dba","oracle developer","oracle ebs","oracle financials","oracle apps"],
		"identity access":["programmer linux python software software","java","python","technical writer","software engineer"],
		"wipro":["cognizant","infosys","hcl","java","igate"],
		"electronics engineer":["electrical engineer"],
		"qa test analyst":["qa tester"],
		"siebel tester":["qa","qa tester"],
		"statistical analyst":["data analyst"],
		"sap analyst":["sap business analyst","sap mm","sap sd","sap bw"],
		"immediate - project manager":["urgent - project manager","project manager- agile/scrum","server administrator","oracle  adf","oracle  apps"],
		"quality assurance":["qa","qa tester","quality assurance analyst","quality assurance manager","tester"],
		"network admin":["network administrator","ccna","network engineer","it","system admin"],
		"manager it":["director it"],
		"peoplesoft hcm":["peoplesoft hrms","peoplesoft developer"],
		"business intelligence analyst":["data analyst","ssrs","informatica"],
		"help desk analyst":["desktop support"],
		"hive":["hadoop","big data","obiee"],
		"geospatial":["gis"],
		"mobile test":["qa"],
		"logistics":["supply chain"],
		"biztalk":[".net","biztalk architect","biztalk developer","java","c"],
		"soa architect":["enterprise architect"],
		"oracle om":["oracle scm"],
		"odi":["oracle data integrator","obiee","owb","etl","hyperion"],
		"video":["software"],
		"sap apo":["sap pp","sap mm","sap sd","sap bw","sap abap"],
		"dynamics":["dynamics ax","dynamics crm"],
		"vmware":["vcp","systems administrator","system administrator","netapp","virtualization"],
		"office assistant":["receptionist","data entry","administrative assistant"],
		"oracle exadata":["oracle dba"],
		"datastage":["datastage developer","etl","cognos","informatica","hadoop"],
		"director of it":["it manager","cio"],
		"birt":["actuate"],
		"access":["vba","ms access","excel","sql","analyst"],
		"vb6":["vb.net"],
		"drools":["java"],
		"exchange":["active directory","system engineer","exchange 2010","lync","iphone developer"],
		"bods":["sap bods","sap data services","business objects data services","sap hana","bidi"],
		"data center technician":["network engineer"],
		"sap gts":["sap sd","sap fico","sap mm"],
		"electronics technician":["linux"],
		"cisco network engineer":["ccna"],
		"test architect":["test manager"],
		"java hadoop":[".net"],
		"vba":["ms access","excel","access","sql","vba developer"],
		"technical":["technical writer","technical support","programmer linux python software software","software engineer","business analyst"],
		"test automation":["qtp"],
		"database tester":["etl tester","qa tester"],
		"talend":["etl","informatica"],
		"microsoft access":["network technician"],
		"cto":["cio","vp","director","vice president","chief technology officer"],
		"sap bw/bi":["sap bw","bw"],
		"production support":["application support","production support analyst","business analyst","autosys","unix support"],
		"erlang":["c"],
		"build release":["scm","configuration manager"],
		"apple":["mac","macintosh"],
		"blizzard":["webmaster .net","trainer"],
		"vblock":["vmware"],
		"siebel business analyst":["healthcare business analyst","sap fico"],
		"sap data migration":["sap data conversion"],
		"software qa analyst":["software qa tester","qa tester"],
		"apo":["sap apo","sap"],
		"cloud":["aws","cloud architect","puppet","openstack","big data"],
		"usb":["support","test"],
		"product owner":["product manager"],
		"desktop support":["help desk","it support","technical support","pc technician","helpdesk"],
		"devops":["linux","aws","java","pmp","c"],
		"sap afs":["sap mm","sap sd"],
		"ssis developers":["ssrs developers","sql bi developers"],
		"vp of engineering":["director of engineering"],
		"jde developer":["jd edwards"],
		"sharepoint developer":[".net developer","sharepoint administrator","java developer","oracle dba","oracle developer"],
		"uat tester":["qa tester","manual tester","qa analyst","qa"],
		"qa automation":["qa analyst","qa tester","java developer","automation engineer","tester"],
		"iis":["sql"],
		"oracle ebs dba":["oracle apps dba","oracle applications dba"],
		"project management":["project manager","project coordinator","business analyst","pmo","program manager"],
		"account":["account manager","sales"],
		"business objects data services":["bods"],
		"iphone  developer":["ios developer","system engineer","mobile developer","mobile application developer","exchange"],
		"erwin":["data modeler"],
		"oracle rms":["oracle retail"],
		"digital engineer":["software"],
		"unix systems administrator":["linux systems administrator"],
		"mechanical engineer":["mechanical design engineer","design engineer"],
		"web producer":["web content"],
		"network   or security":["it project manager","unix"],
		"process":["project manager"],
		"windows support":["desktop support"],
		"tax":["uat","reporting","data analyst","financial analyst","business analyst"],
		"sip":["voip"],
		"it analyst":["systems analyst","business analyst"],
		"sap hr abap":["sap hcm abap","sap hcm"],
		"tableau":["tableau developer","qlikview","business objects","microstrategy","cognos"],
		"windows server administrator":["direct client - java developer","oracle tech","urgent - project manager","project manager- agile/scrum","java gwt"],
		"lamp":["php","linux"],
		"itsm":["itil","remedy","business analyst","program manager","it"],
		"lotus notes":["lotus notes developer","sharepoint","hadoop","oracle","business analyst"],
		"hadoop admin":["hadoop administrator","oracle dba","linux admin","informatica developer","informatica"],
		"administrator":["network","systems administrator","system administrator","engineer","systems"],
		"project analyst":["project coordinator","project manager","business analyst","project management"],
		"software qa":["software tester","software test","software testing","qa tester","software quality"],
		"title:analyst":["analyst"],
		"sap hybris":["sap crm"],
		"business analyst $80,000":["business analyst $80"],
		"hadoop developer":["business analyst","java developer","oracle dba","informatica developer","hadoop administrator"],
		"automation engineer":["qa automation","qa engineer","qa tester","qa analyst","qtp"],
		"grails":["java"],
		"chief":["director","vp","cto","chief technology officer","cio"],
		"healthcare":["health","business analyst","healthcare business analyst","healthcare analyst","ba"],
		"technical project manager":["it project manager","director","scrum master","business analyst","java"],
		"dot net developer":[".net developer","java developer",".net","oracle developer","sap fico"],
		"jira":["jira admin","project manager"],
		"requirements analyst":["business analyst"],
		"sap ppm":["sap plm"],
		"project manager- agile/scrum":["urgent - project manager","java gwt","oracle  adf","oracle functional consultant","oracle tech"],
		"sharepoint manager":["sharepoint architect"],
		"hcl america":["java","cognizant"],
		"tsm":["aix"],
		"java remote":["java telecommute","hadoop remote","hadoop","java spring","it manager"],
		"desktop engineer":["sccm","desktop support","it manager"],
		"peoplesoft technical":["peoplesoft developer"],
		"python":["php","django","java","ruby","c"],
		"pc tech":["desktop support"],
		"dynamics crm":["dynamics ax","microsoft dynamics","sharepoint","c","java"],
		"middleware administrator":["websphere administrator","websphere admin","websphere"],
		"front":["entry"],
		"qa test manager":["qa lead"],
		".net":["c",".net developer","asp.net","java",".net lead"],
		"network director":["network manager"],
		"oracle database":["oracle dba"],
		"clicksoftware":["ventyx","clickschedule"],
		"citrix":["citrix engineer","xenapp","citrix admin","vmware","project manager"],
		"help desk support":["desktop support","help desk technician","technical support","pc technician","helpdesk"],
		"programmer":["developer","software engineer","web developer","software","c"],
		"bpel":["soa","oracle soa"],
		"kforce":["java","qa","teksystems","collabera","experis"],
		"tech support":["help desk","technical support","desktop support","helpdesk","customer support"],
		"ssas":["ssis","ssrs","sql","sql developer","sql server"],
		"sas admin":["sas administrator","remote","cognos","informatica"],
		"systems administrator":["system administrator","systems engineer","network administrator","it manager","vmware"],
		"deloitte":["cognizant"],
		"vmware admin":["cognos","oracle dba"],
		"electronics":["electronics technician","information technology"],
		"math":["mathematics"],
		"sql bi developer":["ssrs developer","sql server developer","ssis developer","etl developer","java developer"],
		"hl7":["hl7 remote","hl7 analyst","healthcare","business analyst","sql"],
		"ecm":["filenet"],
		"payroll":["business analyst"],
		"business object":["business objects","sap bo","business analyst"],
		"filenet":["qlikview","ecm","java","guidewire","business analyst"],
		"3d visualization":["chief data officer","production","python","technical writer","programmer linux python software software"],
		"lte":["umts","rf engineer","testing"],
		"opto mechanical engineer":["webmaster .net"],
		"retail":["business analyst"],
		"performance test engineer":["qa tester"],
		"mongo db":["hadoop"],
		"puppet":["cloud","linux","java"],
		"quality":["qa","quality assurance","test","tester","analyst"],
		"sap le":["sap wm","sap mm","sap sd"],
		"penetration tester":["ceh"],
		"management":["manager"],
		"it supervisor":["it manager"],
		"security director":["security manager"],
		"systel":["hcl","capgemini","cognizant","wipro"],
		"system":["system administrator","network","sap","entry","sybase"],
		"business objects admin":["bo admin","business objects administrator"],
		"java j2ee developer":[".net developer","java/j2ee developer","urgent - project manager","project manager- agile/scrum","java gwt"],
		"oracle hrms":["oracle hcm","oracle hr","oracle ebs","sap abap"],
		"ssis/ssrs developer":["ssrs developer"],
		"security analyst":["information security","information security analyst","it security","business analyst","cissp"],
		"ibm websphere message broker":["java/j2ee"],
		"healthcare it":["project manager"],
		"database manager":["dba manager","oracle dba","it manager"],
		"etl informatica":["informatica developer","java developer","oracle dba","etl developer","cognos"],
		"project server":["sharepoint"],
		"receptionist":["administrative assistant","clerical","office assistant","data entry","customer service"],
		"sap plant maintenance":["sap pm","sap eam"],
		"asp.net":[".net","c","asp.net mvc","mvc",".net developer"],
		"pmo director":["program manager","project manager"],
		"purchasing":["procurement"],
		"java oracle":["urgent - project manager","project manager- agile/scrum","server administrator","oracle  adf","windows administrator"],
		"soap":["selenium","qa"],
		"aws":["cloud","devops","hadoop","informatica","java"],
		"randstad":["modis","business analyst","experis","java","qa analyst"],
		"salesforce admin":["salesforce developer","salesforce administrator","salesforce.com","sfdc","business analyst"],
		"technical writing":["technical writer"],
		"sap sd consultant":["business analyst"],
		"software engineering":["shell","protocol testing","verilog","test","support"],
		"ssrs developer":["ssis developer","sql developer","sql bi developer","sql server developer","ssis/ssrs developer"],
		"xenapp":["citrix"],
		"sap abap":["sap sd","sap crm","sap fico","sap basis","sap bw"],
		"mechanical":["mechanical engineer"],
		"qa manual testing":["qa tester","manual tester","qa manual tester","qa analyst","sap mm"],
		"loadrunner":["qa","performance tester","performance","performance testing","performance engineer"],
		"healthcare analyst":["healthcare business analyst","business analyst","data analyst"],
		"immediate - java developer":["java gwt","urgent - java developer","oracle tech","urgent - project manager","oracle functional consultant"],
		"vcap":["vmware"],
		"clinical sas":["sas programmer","java"],
		"it management":["it manager","it director"],
		"network architect":["network engineer"],
		"product analyst":["business analyst"],
		"servicenow":["service-now","servicenow remote","service now","itil","oracle dba"],
		"desktop support technician":["pc technician","computer technician","help desk"],
		"vp technology":["cio","cto"],
		"mmis":["medicaid","healthcare"],
		"prokarma":[".net"],
		"vdi":["vmware"],
		"java backend":["java developer"],
		"talent acquisition":["recruiter"],
		"business analyst healthcare":["business analyst finance","quality analyst","ba","business analyst insurance","qa tester"],
		"itil":["business analyst","itsm","change management","it manager","project manager"],
		"db2":["db2 dba","cobol","mainframe","java","dba"],
		"oracle application":["oracle apps","oracle functional","oracle ebs"],
		"mobile testing":["mobile tester","manual testing","qa tester","qa","qa analyst"],
		"qt":["c"],
		"windows system administrator":["systems administrator","windows systems administrator","windows server administrator","network administrator","vmware"],
		"a+ certification":["help desk"],
		"qa":["qa tester","business analyst","qa analyst","tester","quality assurance"],
		"qc":["qa"],
		"qatester":["qa tester"],
		"aem":["cq5"],
		"cognos":["cognos developer","informatica","business intelligence","hadoop","datastage"],
		"qtp":["qa","qa tester","selenium","manual tester","tester"],
		"sap ehs":["sap eh","sap plm","sap ehsm","sap pp","sap bi"],
		"abinitio developer":["ab initio developer","oracle dba",".net developer","etl developer","java developer"],
		"director technology":["cio","vice president technology","cto","c"],
		"computer":["help desk","information technology","computer technician","desktop","technical support"],
		"system administration":["system administrator"],
		"ebs":["oracle ebs","oracle"],
		"hbase":["hadoop"],
		"sap developer":["sap abap","abap","java developer"],
		"synon":["rpg","as400"],
		"mobile manual testing":["c"],
		"support engineer":["technical support engineer"],
		"verilog":["asic","fpga","software engineering","shell","protocol testing"],
		"oracle r12":["oracle ebs","oracle financials","oracle apps","oracle applications","oracle erp"],
		"tentek":["business analyst"],
		"sales force":["salesforce","salesforce developer","datastage","informatica","selenium"],
		"network analyst":["network administrator","network engineer","ccna"],
		"configuration":["release","configuration manager"],
		"c# $130":["c"],
		"enovia":["informatica","sas"],
		"sap payroll":["sap hcm","sap hr","sap time","sap hana","sap bw"],
		"it help desk":["it support"],
		"service now":["servicenow","oracle dba","itil","salesforce","cognos"],
		"core java":["java developer"],
		"etl":["informatica","etl developer","ssis","datastage","teradata"],
		"sap program manager":["sap project manager","sap director"],
		"informatica etl developer":["qa analyst"],
		"ucs":["vmware"],
		"peoplesoft upgrade":["peoplesoft dba","peoplesoft administrator"],
		"software test engineer":["qa tester","qa engineer","software tester","software qa engineer","qa"],
		"edi":["edi analyst","sterling integrator","gentran","sap edi","edi remote"],
		"hadoop administrator":["hadoop admin","hadoop developer","business analyst"],
		"rpg":["as400","rpg programmer","iseries","as/400","synon"],
		"sql tester":["qa tester","etl qa","etl tester","qa analyst","manual tester"],
		"data stage":["datastage","oracle dba"],
		"cq":["sas"],
		"asp.net mvc":[".net","c"],
		"mathematics":["math"],
		"qa director":["qa manager","test manager","peoplesoft","qa lead"],
		"sap hcm abap":["sap hr abap"],
		"intelligence analyst":["afghanistan"],
		"c#":["c",".net","software engineer","asp.net","wpf"],
		"j2ee":["java","java j2ee","qa","atg","business analyst"],
		"sas programmer":["clinical sas programmer","sas developer","sas clinical","sas analyst","sas data analyst"],
		"ilog":["wodm","sap solution manager","java"],
		"software quality assurance":["software tester","software testing","manual tester","qa tester","software qa"],
		"oracle order management":["oracle configurator","oracle apps","oracle scm","oracle supply chain","oracle ebs"],
		"desktop technician":["desktop support","help desk"],
		"build engineer":["release engineer","technical lead","configuration manager","release manager","build and release engineer"],
		"storage engineer":["emc storage","storage administrator","system engineer"],
		"remote dba":["oracle dba"],
		"health care":["healthcare"],
		"qa healthcare":["qa tester","tester","business analyst","ba","qa analyst"],
		"healthcare business analyst":["facets","health care business analyst","qa","qa lead","siebel business analyst"],
		"crystal reports":["business objects","crystal report","bo","sap bo","crystal reports developer"],
		"plsql developer":["oracle developer","oracle","oracle pl sql developer","oracle dba"],
		"accenture":["wipro"],
		"vb":["visual basic","asp","vba","vb.net","c"],
		"automation testing":["qtp","manual testing","automation tester","qa","selenium"],
		"vp":["director","cto","cio","chief","vice"],
		"db2 dba":["oracle dba","informatica","mainframe","java","websphere"],
		"business objects developer":["bo developer",".net developer","sap bo developer","informatica developer","sql server developer"],
		"apps dba":["oracle apps dba","oracle dba","oracle"],
		"data tester":["qa tester"],
		"ssis/ssrs":["java"],
		"manager software":["programmer linux python software software","python","sap crm e-commerce","software engineer","chief data officer"],
		"application development manager":["software development manager","software manager","it manager"],
		"android":["android developer","ios","java","mobile","c"],
		"web development":["web developer","front end developer"],
		"pmo manager":["project manager"],
		"six sigma":["project manager","business analyst"],
		"reporting":["tax","analyst","business analyst","reporting analyst","sql"],
		"upon":["forth"],
		"automation":["selenium","qtp","java","qa","qa lead"],
		"sap mm":["sap sd","sap fico","sap wm","sap pp","sap abap"],
		"mysql dba":["oracle dba"],
		"php":["php developer","python","drupal","java","javascript"],
		"identity":["iam"],
		"database administrator":["oracle dba","oracle database administrator","dba","sql dba","sql server dba"],
		"weld":["novell or netiq","unix","medicaid"],
		"data center":["software","data center manager","noc","data center engineer","oracle"],
		"procurement":["purchasing","business analyst","hadoop"],
		"sap fi co":["sap fico"],
		"cognos tm1":["cognos developer","business analyst"],
		"mfc":["c"],
		"sdet":["tester","qa","test","c","java"],
		"camel":["enterprise integration patterns","servicemix","qa tester","java"],
		"it program manager":["it project manager","it director","linux","unix","director"],
		"requirement analyst":["business analyst"],
		"tcs":["wipro"],
		"database developer":["sql developer","sql","oracle developer","sql server","sql server developer"],
		"abap":["sap abap","sap","webdynpro","sap bw","abap remote"],
		"web":["web developer","php","html","software","web designer"],
		"windows systems administrator":["windows system administrator","system administrator","desktop support"],
		"adf":["oracle soa","weblogic","oracle adf","java","oracle dba"],
		"remote work":["work from home"],
		"quality engineer":["qa engineer","qa","qa tester"],
		"plsql":["pl/sql","oracle","pl sql","sql","oracle pl/sql"],
		"c# .net":["c"],
		"recent grad":["entry level"],
		"administrative assistant":["receptionist","executive assistant","secretary","clerical","office manager"],
		"deployment":["desktop"],
		"dba manager":["database manager","oracle dba","it manager"],
		"adabas":["cobol","mainframe"],
		"oracle service bus":["java"],
		"insight global":["java developer"],
		"sales force developer":["salesforce developer"],
		"classic asp":["guidewire","informatica","release manager","qa lead","qa"],
		"director of engineering":["vp of engineering"],
		"network support":["desktop support","network administrator","network technician","ccna","help desk"],
		". net developer":[".net developer"],
		"part time":["remote","parttime","security","weekend","part-time"],
		"lead":["architect","manager","director"],
		"oracle architect":["oracle dba"],
		"vp it":["cio","it director","director it","director"],
		"esb":["soa","java"],
		"information security":["security analyst","cissp","information security analyst","information assurance","systems administrator"],
		"data analysis":["data analyst"],
		"22nd century technologies":["gatto"],
		"director ucla":["webmaster .net"],
		"qa remote":["qa manager","qa tester","qa lead"],
		"enterprise integration patterns":["camel","servicemix"],
		"tm1":["cognos","pl sql","business analyst","qa"],
		"ios developer":["mobile developer","iphone developer","system engineer","mobile application developer","iphone  developer"],
		"arcgis":["gis"],
		"windows migration":["desktop support"],
		"sap time":["sap payroll"],
		"team lead":["java"],
		"software":["java","software engineer","engineering","software developer","unix"],
		"soa admin":["weblogic admin"],
		"owb":["odi","etl","qa","informatica"],
		"etl analyst":["data analyst","etl developer"],
		"networking":["network","help desk","network administrator","it"],
		"recruiter":["technical recruiter","it recruiter","hr","contract recruiter","virtual recruiter"],
		"sap fscm":["sap fico","sap fi","sap abap"],
		"hrms":["hcm","hris","oracle hrms"],
		"product manager":["project manager","program manager","business analyst","product management","product owner"],
		".net remote":["c","java"],
		"oracle inventory":["oracle wms","oracle functional"],
		"hr":["human resources","recruiter","hris","business analyst","qa tester"],
		"hp":["business analyst"],
		"qa automation engineer":["qa tester"],
		"technician":["help desk","electronics technician","support","network","desktop"],
		"sap business analyst":["sap sd","sap fico","sap mm","sap abap"],
		"hris":["hcm","hr","hrms","workday","business analyst"],
		"support analyst":["technical support"],
		"lync":["exchange"],
		"oracle applications":["oracle ebs","oracle apps","oracle r12","oracle financials","oracle erp"],
		"support manager":["help desk manager","it manager"],
		"director it":["it manager","vp it","manager it","program manager","director information technology"],
		"pig":["hadoop"],
		"desktop administrator":["system administrator","systems administrator"],
		"fusion middleware":["cognos","etl informatica","oracle soa","siebel","soa"],
		"linux administrator":["linux admin","unix administrator","linux system administrator","system administrator","systems administrator"],
		"sap ess":["sap hr"],
		"validation tester":["qa analyst","qa tester"],
		"informatica architect":["sap treasury","sap srm","cognos","informatica developer","sap fico"],
		"oaf":["oracle"],
		"oam":["oim","ldap","weblogic"],
		"virtual":["remote","telecommute","work from home"],
		"peoplesoft":["peoplesoft hcm","peoplesoft developer","peoplesoft remote","peoplesoft financials","peoplesoft tester"],
		"ca gen":["coolgen"],
		"autosys":["unix support","production support","trade support","pl/sql","qa"],
		"java, j2ee":["java"],
		"cognos admin":["cognos administrator","java"],
		"extjs":["ext js","java"],
		"xamarin":["c",".net"],
		"validation":["validation engineer","computer system validation","csv","test","sap"],
		"parttime":["part time"],
		"oracle supply chain":["oracle scm","oracle order management"],
		"bi developer":["ssrs","sql developer","etl developer","ssis","sql server developer"],
		"exadata":["oracle dba","oracle","java"],
		"business analyst finance":["business analyst healthcare","business analyst insurance","business analyst banking","sap fico","java developer"]
	};
	return mlt;
}